# Generated by Django 4.0.6 on 2022-07-31 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=256, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
